config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount MindleapsAnalytics::Engine, at: '/analytics' if defined?(MindleapsAnalytics)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }, path: '/'
  devise_scope :user do
    post 'sign_in', to: 'users/sessions#token_signin'
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticate :user, ->(user) { user.is_super_admin? } do
    mount PgHero::Engine, at: 'pghero'
  end

  scope module: :api, as: :api, constraints: ->(req) { req.format == :json } do
    resources :organizations, only: %i[index show]
    resources :chapters, only: %i[index show]
    resources :groups, only: %i[index show]
    resources :students, only: %i[index show]
    resources :lessons, only: %i[index show create]
    resources :grades, only: %i[show create index update destroy]
    resources :subjects, only: %i[index show]
    resources :skills, only: %i[index show]
    resources :grade_descriptors, only: %i[index show]
    resources :assignments, only: %i[index show]
  end

  resources :users, only: %i[index new create show] do
    resources :memberships, only: %i[update destroy] do
      put :update_global_role, on: :collection
      delete :revoke_global_role, on: :collection
    end
  end
  resources :organizations, only: %i[index new create show] do
    member { post :add_member }
  end
  resources :chapters, only: %i[index new create show edit update]
  resources :groups, only: %i[index new create show edit update destroy] do
    member { post :undelete }
  end
  resources :students, only: %i[index new create show edit update destroy] do
    resources :student_images, only: %i[index create]
    member do
      post :undelete
    end
  end
  resources :lessons, only: %i[index new create show] do
    resources :students, controller: :student_lessons, only: %i[show update]
  end
  resources :subjects, only: %i[index new create show edit update]
  resources :skills, only: %i[index create show new]

  root to: 'home#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :authentication_tokens, dependent: :destroy
  rolify before_add: :before_add_role, strict: true
  validates :email, presence: true
  validates :email, uniqueness: true, allow_blank: true

  devise :trackable, :token_authenticatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def role_level_in(organization)
    levels = roles.global.map(&:level)
    levels << local_role_level_in(organization)
    levels.max
  end

  def role_in(organization)
    # Returns only an explicit role in the passed organization, not including global roles
    roles.find_by resource_id: organization.id
  end

  def administrator?(organization = nil)
    is_admin_of?(organization) || global_administrator?
  end

  def global_role?
    roles.global.present?
  end

  def global_role
    roles.global.first
  end

  def organizations
    return Organization.all if global_role?

    membership_organizations
  end

  def global_administrator?
    is_global_admin? || is_super_admin?
  end

  def membership_organizations
    # All organizations in which this user has an explicit role, not including global roles
    Organization.where(id: roles.pluck(:resource_id))
  end

  def member_of?(organization)
    roles.pluck(:resource_id).include?(organization.id)
  end

  def read_only?
    (roles.pluck(:name).map(&:to_sym) - Role::READ_ONLY_ROLES).empty?
  end

  private

  def before_add_role(role)
    raise ActiveRecord::Rollback if Role::LOCAL_ROLES[role.symbol].nil? && Role::GLOBAL_ROLES[role.symbol].nil?
    raise ActiveRecord::Rollback if roles.pluck(:resource_id).include?(role.resource_id)
  end

  def local_role_level_in(organization)
    # Role level in explicit organization, excluding global roles
    role = role_in organization
    return Role::MINIMAL_ROLE_LEVEL if role.nil?
    role.level
  end

  class << self
    def from_omniauth(auth)
      user = get_user_from_auth auth
      return update_user_from_omniauth user, auth if user
      return create_first_user auth if first_user?
      empty_user
    end

    def from_id_token(id_token)
      client = OAuth2::Client.new(Rails.configuration.google_client_id, Rails.configuration.google_client_secret)

      response = client.request(:get, Rails.configuration.google_token_info_url, params: { id_token: id_token }).parsed
      User.find_by(email: response['email'])
    end

    private

    def update_user_from_omniauth(user, auth)
      user.update auth_params auth
      user
    end

    def empty_user
      User.new
    end

    def create_first_user(auth)
      user = User.new auth_params auth
      user.save
      user.add_role :super_admin
      user
    end

    def get_user_from_auth(auth)
      User.find_by email: auth['info']['email']
    end

    def first_user?
      User.count.zero?
    end

    def auth_params(auth)
      {
        uid: auth['uid'],
        name: auth['info']['name'],
        email: auth['info']['email'],
        provider: auth.provider,
        image: auth['info']['image']
      }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :authenticate_user!

    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: '  Google') if is_navigational_format?
      else
        failure
      end
    end

    def failure
      flash[:alert] = I18n.t('devise.failure.unauthenticated')
      redirect_to root_path
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    skip_before_action :verify_authenticity_token

    def token_signin
      user = authenticate_user_from_token! params[:id_token].presence
      return render json: { error: I18n.t(:invalid_token) }, status: :unauthorized if user.nil?

      token = Tiddle.create_and_return_token(user, request)
      render json: { authentication_token: token }
    end

    private

    def authenticate_user_from_token!(token)
      return nil unless token
      user = User.from_id_token(token.to_s)
      sign_in user, store: false if user
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action do
    @users = policy_scope User.all
  end

  def index
    authorize User
  end

  def new
    authorize User
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:email)
    authorize @user
    return notice_and_redirect(t(:user_added, email: params[:user][:email]), users_url) if @user.save
    render :index
  end

  def show
    @user = User.find params[:id]
    @membership = Membership.new user: @user
    authorize @user
  end
end

app/views/users/index.slim
= content_for :header_content do
  = render layout: '/shared/header_content', locals: {title: 'Users'} do
    = render partial: '/shared/main_header_button', locals: {href: new_user_path, title: 'Add User'}

.single-content-card
  = render partial: 'shared/users_table', locals: { users: @users }

app/views/users/new.slim
- content_for :header_content do
  = render partial: '/shared/header_content', locals: {back_button_url: users_path, back_tooltip: 'Back to Users', title: 'New User'}

.content-card--most.center
  = simple_form_for @user, url: {action: 'create'} do |f|
    = render partial: 'shared/errors', locals: {subject: @user}
    = f.input :email
    = f.button :submit, class: 'mdl-button--raised mdl-button--accent mdl-js-ripple-effect'

app/views/users/show.slim
- content_for :header_content do
  = render partial: '/shared/header_content', locals: { back_button_url: users_path, back_tooltip: 'Back to Users', title: user_name(@user) }
.mdl-cell.mdl-cell--4-col
  .mdl-card.mdl-shadow--2dp.user-profile-card
    .mdl-card__title.primary
      = image_tag user_image(@user, 300), class: 'profile-image'
      br
      h2.mdl-card__title-text = user_name @user
    .mdl-card__supporting-text
      ul
        li Email: #{@user.email}
      h4 Global role:
      - if @user.global_role?
        p #{@user.roles.global.first.label}
      - else
        p No Global Role
      h4 Organization Roles:
      ul
        - @user.roles.includes(:resource).instance_scoped(Organization).each do |role|
          li #{role.resource.organization_name}: #{Role::LOCAL_ROLES[role.name.to_sym]}

- if @user.id != current_user.id && policy(@membership).update_global_role?
  .mdl-cell.mdl-cell--4-col
    .mdl-card.mdl-shadow--2dp.role-administration-card
      .mdl-card__title.primary
        h2.mdl-card__title-text Global Roles
      = simple_form_for @membership, url: update_global_role_user_memberships_path(@user), as: 'global-role-form', method: :put, html: { id: "user-roles-global" } do |f|
        / = f.input :role, as: :radio_buttons, collection: Role::GLOBAL_ROLES.invert
        .mdl-card__supporting-text
          - Role::GLOBAL_ROLES.each do |role_value, role_name|
            label class='mdl-radio mdl-js-radio mdl-js-ripple-effect global-role-radio'
              = radio_button_tag role_value, role_value.to_s, user_global_role(@user) == role_value, name: "role", class: "mdl-radio__button"
              span class='mdl-radio__label' = role_name
        <div class="mdl-card__actions mdl-card--border role-actions">
          = f.button :submit, t(:update_global_role_button), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect'
      = button_to t(:revoke_global_role_button), revoke_global_role_user_memberships_path(@user), method: :delete, class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect button--danger' if @user.global_role?
      </div>
  .mdl-cell.mdl-cell--4-col
    .mdl-card.mdl-shadow--2dp.role-administration-card
      .mdl-card__title.primary
        h2.mdl-card__title-text Organization Roles
      - current_user.organizations.each do |org|
        - if policy(Membership.new(user: @user, org: org)).update?
          = simple_form_for @membership, url: user_membership_path(@user, org), method: :put, html: { id: "user-roles-for[#{org.id}]" } do |f|
            .mdl-card__supporting-text
              h4 = org.organization_name
              - Role::LOCAL_ROLES.each do |role_value, role_name|
                label class='mdl-radio mdl-js-radio mdl-js-ripple-effect global-role-radio'
                  = radio_button_tag role_value, role_value.to_s, user_role_in(@user, org) == role_value, name: "role", class: "mdl-radio__button"
                  span class='mdl-radio__label' = role_name
            <div class="mdl-card__actions mdl-card--border role-actions">
              = f.button :submit, t(:update_role_button), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect'
          = button_to t(:revoke_local_role_button, org: org.organization_name), user_membership_path(@user, org), method: :delete, class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect button--danger' if @user.member_of?(org)
          </div>