config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount MindleapsAnalytics::Engine, at: '/analytics' if defined?(MindleapsAnalytics)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }, path: '/'
  devise_scope :user do
    post 'sign_in', to: 'users/sessions#token_signin'
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticate :user, ->(user) { user.is_super_admin? } do
    mount PgHero::Engine, at: 'pghero'
  end

  scope module: :api, as: :api, constraints: ->(req) { req.format == :json } do
    resources :organizations, only: %i[index show]
    resources :chapters, only: %i[index show]
    resources :groups, only: %i[index show]
    resources :students, only: %i[index show]
    resources :lessons, only: %i[index show create]
    resources :grades, only: %i[show create index update destroy]
    resources :subjects, only: %i[index show]
    resources :skills, only: %i[index show]
    resources :grade_descriptors, only: %i[index show]
    resources :assignments, only: %i[index show]
  end

  resources :users, only: %i[index new create show] do
    resources :memberships, only: %i[update destroy] do
      put :update_global_role, on: :collection
      delete :revoke_global_role, on: :collection
    end
  end
  resources :organizations, only: %i[index new create show] do
    member { post :add_member }
  end
  resources :chapters, only: %i[index new create show edit update]
  resources :groups, only: %i[index new create show edit update destroy] do
    member { post :undelete }
  end
  resources :students, only: %i[index new create show edit update destroy] do
    resources :student_images, only: %i[index create]
    member do
      post :undelete
    end
  end
  resources :lessons, only: %i[index new create show] do
    resources :students, controller: :student_lessons, only: %i[show update]
  end
  resources :subjects, only: %i[index new create show edit update]
  resources :skills, only: %i[index create show new]

  root to: 'home#index'
end

app/views/shared/_danger_header_button.slim
a class='header-button button--danger mdl-button mdl-js-button mdl-button--raised colored mdl-js-ripple-effect' href=href
  = title

app/views/shared/_groups_table.slim
table class="mdl-data-table mdl-js-data-table resource-table"
  thead
    tr
      th class="mdl-data-table__cell--non-numeric"
        | Group Name
      th class="mdl-data-table__cell--non-numeric"
        | Chapter
      th
        | Number of Students
  - groups.each do |group|
    tr class="resource-row group-row"
      td.mdl-data-table__cell--non-numeric
        = link_to group.group_name, group
      td.mdl-data-table__cell--non-numeric
        = link_to group_chapter_name(group), group
      td
        = link_to group.students.length, group

app/views/shared/_header_content.slim
- if defined? back_button_url
  a id="back-button" href=back_button_url class="mdl-button mdl-js-button mdl-button--icon unset-color"
    = inline_svg 'arrow_back.svg'
  - if defined? back_tooltip
    .mdl-tooltip data-mdl-for="back-button" = back_tooltip

span.mdl-layout-title = title

= yield

app/views/shared/_lessons_table.slim
table class='mdl-data-table mdl-js-data-table resource-table'
  thead
    tr
      th class='mdl-data-table__cell--non-numeric' Group Name
      th class='mdl-data-table__cell--non-numeric' Date
      th class='mdl-data-table__cell--non-numeric' Subject

  - lessons.each do |lesson|
    tr class='resource-row'
      td class='mdl-data-table__cell--non-numeric'
        = link_to lesson.group.group_name, lesson_path(lesson)
      td class='mdl-data-table__cell--non-numeric'
        = link_to lesson.date, lesson_path(lesson)
      td class='mdl-data-table__cell--non-numeric'
        = link_to lesson.subject.subject_name, lesson_path(lesson)

app/views/shared/_main_header_button.slim
a class='header-button mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect' href=href
  = title

app/views/shared/_main_nav_item.slim
a class="mdl-navigation__link nav-link#{current_page?(url) ? ' mdl-navigation__link--current' : ' mdl-js-button mdl-js-ripple-effect'}" disabled=('disabled' if current_page?(url)) href=(url unless current_page?(url))
  = inline_svg svg_icon, class: 'nav-icon'
  = name

app/views/shared/_members_table.slim
table class='mdl-data-table mdl-js-data-table resource-table'
  thead
    tr
      th class='mdl-data-table__cell--non-numeric'
        | Member Name
      th class='mdl-data-table__cell--non-numeric'
        | Roles
  - members.each do |member|
    tr class='resource-row'
      td class='mdl-data-table__cell--non-numeric'
        = link_to name_or_email(member), user_path(member)
      td class='mdl-data-table__cell--non-numeric'
        = link_to member.roles.map(&:label).join(', '), user_path(member)

app/views/shared/_neutral_header_button.slim
a class='header-button button--neutral mdl-button mdl-js-button mdl-button--raised colored mdl-js-ripple-effect' href=href
  = title

app/views/shared/_skill_form.slim
= simple_form_for skill, url: {action: 'create'} do |f|
  = render partial: 'shared/errors', locals: {subject: skill}
  = f.input :skill_name
  = f.association :organization, label_method: :organization_name, include_blank: false
  br
  = f.input :skill_description
  h5 Grade Descriptors
  = f.simple_fields_for :grade_descriptors do |grade_descriptors|
    = render 'grade_descriptor_fields', f: grade_descriptors
  div.new-grade-descriptor-container
    = link_to_add_association f, :grade_descriptors do
      button class='mdl-button mdl-button--primary mdl-js-button mdl-js-ripple-effect' Add Grade Descriptor
  = f.button :submit, class: 'mdl-button--raised mdl-button--accent mdl-js-ripple-effect form-submit'

app/views/shared/_snackbar.slim
- if notice or link_notice or undo_notice or alert
  .snackbar-wrapper
    .snackbar
      - if notice
        = notice
      - if link_notice
        = link_notice.try(:html_safe)
      - if undo_notice
        = undo_notice['text']
        = button_to 'Undo', undo_notice['path'], class: 'snackbar-action-button mdl-js-button'
      - if alert
        = alert

app/views/shared/_students_table.slim
table class='mdl-data-table mdl-js-data-table resource-table'
  thead
    tr
      th class="mdl-data-table__cell--non-numeric"
        | MLID
      th class="mdl-data-table__cell--non-numeric"
        | Image
      th class="mdl-data-table__cell--non-numeric"
        | Last Name
      th class="mdl-data-table__cell--non-numeric"
        | First Name
      th class="mdl-data-table__cell--non-numeric"
        | Gender
      th class="mdl-data-table__cell--non-numeric"
        | Date of Birth
      th class="mdl-data-table__cell--non-numeric"
        | Group
  - students.each do |student|
    tr class='resource-row'
      td class="mdl-data-table__cell--non-numeric"
        = link_to student.mlid, student_path(student)
      td class="mdl-data-table__cell--non-numeric"
        = link_to image_tag(student_mini_thumbnail(student), alt: 'profile image', class: 'mini-thumb-profile-image'), student_path(student)
      td class="mdl-data-table__cell--non-numeric"
        = link_to student.last_name, student_path(student)
      td class="mdl-data-table__cell--non-numeric"
        = link_to student.first_name, student_path(student)
      td class="mdl-data-table__cell--non-numeric"
        = link_to student.gender_i18n, student_path(student)
      td class="mdl-data-table__cell--non-numeric"
        = link_to "#{student.dob} #{student.estimated_dob ? 'EST' : ''}", student_path(student)
      td class="mdl-data-table__cell--non-numeric"
        = link_to student_group_name(student), student_path(student)

app/views/shared/_subject_form.slim
= simple_form_for @subject, url: {action: action} do |f|
  = render partial: 'shared/errors', locals: {subject: @subject}
  = f.input :subject_name
  = f.association :organization, label_method: :organization_name, include_blank: false
  h5 Skills
  = f.simple_fields_for :assignments do |assignment|
    = render 'assignment_fields', f: assignment
  div.new-skill-container
    = link_to_add_association f, :assignments do
      button class='mdl-button mdl-button--primary mdl-js-button mdl-js-ripple-effect'
        | Add Skill
  = f.button :submit, class: 'mdl-button--raised mdl-button--accent mdl-js-ripple-effect form-submit'

app/views/shared/_users_table.slim
table class='mdl-data-table mdl-js-data-table resource-table'
  thead
    tr
      th class='mdl-data-table__cell--non-numeric'
        | Name
      th class='mdl-data-table__cell--non-numeric'
        | E-mail
      th class='mdl-data-table__cell--non-numeric'
        | Global Role
  - users.each do |user|
    tr class='resource-row'
      td class='mdl-data-table__cell--non-numeric'
        = link_to user_name(user), user_path(user)
      td class='mdl-data-table__cell--non-numeric'
        = link_to user.email, user_path(user)
      td class='mdl-data-table__cell--non-numeric'
        = link_to user.global_role? ? user.global_role.label : 'None', user_path(user)