config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount MindleapsAnalytics::Engine, at: '/analytics' if defined?(MindleapsAnalytics)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }, path: '/'
  devise_scope :user do
    post 'sign_in', to: 'users/sessions#token_signin'
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticate :user, ->(user) { user.is_super_admin? } do
    mount PgHero::Engine, at: 'pghero'
  end

  scope module: :api, as: :api, constraints: ->(req) { req.format == :json } do
    resources :organizations, only: %i[index show]
    resources :chapters, only: %i[index show]
    resources :groups, only: %i[index show]
    resources :students, only: %i[index show]
    resources :lessons, only: %i[index show create]
    resources :grades, only: %i[show create index update destroy]
    resources :subjects, only: %i[index show]
    resources :skills, only: %i[index show]
    resources :grade_descriptors, only: %i[index show]
    resources :assignments, only: %i[index show]
  end

  resources :users, only: %i[index new create show] do
    resources :memberships, only: %i[update destroy] do
      put :update_global_role, on: :collection
      delete :revoke_global_role, on: :collection
    end
  end
  resources :organizations, only: %i[index new create show] do
    member { post :add_member }
  end
  resources :chapters, only: %i[index new create show edit update]
  resources :groups, only: %i[index new create show edit update destroy] do
    member { post :undelete }
  end
  resources :students, only: %i[index new create show edit update destroy] do
    resources :student_images, only: %i[index create]
    member do
      post :undelete
    end
  end
  resources :lessons, only: %i[index new create show] do
    resources :students, controller: :student_lessons, only: %i[show update]
  end
  resources :subjects, only: %i[index new create show edit update]
  resources :skills, only: %i[index create show new]

  root to: 'home#index'
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  belongs_to :organization
  has_many :lessons, dependent: :restrict_with_error
  has_many :assignments, -> { exclude_deleted }, inverse_of: :subject, dependent: :destroy
  has_many :skills, through: :assignments, dependent: :destroy, inverse_of: :subjects

  validates :subject_name, :organization, presence: true

  scope :by_organization, ->(organization_id) { where organization_id: organization_id }

  accepts_nested_attributes_for :assignments, allow_destroy: true
end

app/controllers/api/subjects_controller.rb
# frozen_string_literal: true

module Api
  class SubjectsController < ApiController
    has_scope :after_timestamp

    has_scope :by_organization, as: :organization_id

    def index
      @subjects = apply_scopes(Subject).all
      respond_with @subjects, include: included_params, meta: { timestamp: Time.zone.now }
    end

    def show
      @subject = Subject.find params.require 'id'
      respond_with @subject, include: included_params, meta: { timestamp: Time.zone.now }
    end
  end
end

app/controllers/subjects_controller.rb
# frozen_string_literal: true

class SubjectsController < ApplicationController
  def index
    authorize Subject
    @subjects = policy_scope Subject.includes(:assignments, :skills, :organization)
  end

  def new
    authorize Subject
    @subject = Subject.new
  end

  def create
    @subject = Subject.new subject_params
    authorize @subject
    return notice_and_redirect(t(:subject_created, subject: @subject.subject_name), subjects_url) if @subject.save
    render :index
  end

  def show
    @subject = Subject.includes(assignments: [:skill]).find params.require(:id)
    authorize @subject
  end

  def edit
    @subject = Subject.includes(:assignments).find params.require(:id)
    authorize @subject
  end

  def update
    subject = Subject.includes(:organization).find params.require(:id)
    authorize subject
    notice_and_redirect(t(:subject_updated), subject) if subject.update subject_params
  end

  private

  def subject_params
    params.require(:subject).permit :subject_name, :organization_id, assignments_attributes: %i[id skill_id _destroy]
  end
end

app/views/subjects/_assignment_fields.slim
div.nested-fields
  = f.association :skill, label_method: :skill_name, include_blank: false
  = link_to_remove_association f, class:'mdl-button mdl-js-button mdl-button--icon mdl-button--colored' do
    = inline_svg 'delete_forever.svg'

app/views/subjects/_subjects_table.slim
table class='mdl-data-table mdl-js-data-table resource-table'
  thead
    tr
      th class='mdl-data-table__cell--non-numeric' Subject Name
      th class='mdl-data-table__cell--non-numeric' Organization
      th class='mdl-data-table__cell--non-numeric' Skills
  - subjects.each do |subject|
    tr class='resource-row'
      td class='mdl-data-table__cell--non-numeric'
        = link_to subject.subject_name, subject_path(subject)
      td class='mdl-data-table__cell--non-numeric'
        = link_to subject.organization.organization_name, subject_path(subject)
      td class='mdl-data-table__cell--non-numeric'
        = link_to subject.skills.length, subject_path(subject)

app/views/subjects/edit.slim
- content_for :header_content do
  = render partial: '/shared/header_content', locals: { back_button_url: subjects_path, back_tooltip: 'Back to Users', title: @subject.subject_name }

.content-card--most.center
  = render partial: 'shared/subject_form', locals: { subject: @subject, action: :update }

app/views/subjects/index.slim
- content_for :header_content do
  = render layout: '/shared/header_content', locals: {title: 'Subjects'} do
    = render partial: '/shared/main_header_button', locals: {href: new_subject_path, title: 'Add Subject'}

.single-content-card
  = render partial: "subjects/subjects_table", locals: {subjects: @subjects}

app/views/subjects/new.slim
- content_for :header_content do
  = render partial: '/shared/header_content', locals: { back_button_url: subjects_path, back_tooltip: 'Back to Subjects', title: 'New Subject' }

.content-card--most.center
  = render partial: 'shared/subject_form', locals: {subject: @subject, action: 'create'}

app/views/subjects/show.slim
- content_for :header_content do
  = render partial: '/shared/header_content', locals: { back_button_url: subjects_path, back_tooltip: 'Back to Subjects', title: @subject.subject_name }

- content_for :header_actions do
  - if policy(@subject).edit?
    a href=edit_subject_path(@subject) id='edit-button' class='mdl-button mdl-js-button mdl-button--icon'
      = inline_svg 'edit.svg'
    .mdl-tooltip data-mdl-for='edit-button' Edit Subject

.single-content-card
  - if @subject.skills.size > 0
    h4 Skills:
    ul
      - @subject.skills.each do |skill|
        li = skill.skill_name
  - else
    h4 No skills present in subject