config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount MindleapsAnalytics::Engine, at: '/analytics' if defined?(MindleapsAnalytics)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }, path: '/'
  devise_scope :user do
    post 'sign_in', to: 'users/sessions#token_signin'
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticate :user, ->(user) { user.is_super_admin? } do
    mount PgHero::Engine, at: 'pghero'
  end

  scope module: :api, as: :api, constraints: ->(req) { req.format == :json } do
    resources :organizations, only: %i[index show]
    resources :chapters, only: %i[index show]
    resources :groups, only: %i[index show]
    resources :students, only: %i[index show]
    resources :lessons, only: %i[index show create]
    resources :grades, only: %i[show create index update destroy]
    resources :subjects, only: %i[index show]
    resources :skills, only: %i[index show]
    resources :grade_descriptors, only: %i[index show]
    resources :assignments, only: %i[index show]
  end

  resources :users, only: %i[index new create show] do
    resources :memberships, only: %i[update destroy] do
      put :update_global_role, on: :collection
      delete :revoke_global_role, on: :collection
    end
  end
  resources :organizations, only: %i[index new create show] do
    member { post :add_member }
  end
  resources :chapters, only: %i[index new create show edit update]
  resources :groups, only: %i[index new create show edit update destroy] do
    member { post :undelete }
  end
  resources :students, only: %i[index new create show edit update destroy] do
    resources :student_images, only: %i[index create]
    member do
      post :undelete
    end
  end
  resources :lessons, only: %i[index new create show] do
    resources :students, controller: :student_lessons, only: %i[show update]
  end
  resources :subjects, only: %i[index new create show edit update]
  resources :skills, only: %i[index create show new]

  root to: 'home#index'
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  belongs_to :group
  belongs_to :subject
  has_many :absences, dependent: :restrict_with_error
  has_many :grades, dependent: :restrict_with_error

  validates :group, :date, :subject, presence: true
  scope :by_group, ->(group_id) { where group_id: group_id }
  scope :by_subject, ->(subject_id) { where subject_id: subject_id }

  validates :date, uniqueness: {
    scope: %i[group subject],
    message: ->(object, _data) { I18n.translate :duplicate_lesson, group: object.group.group_name, subject: object.subject.subject_name }
  }

  def mark_student_as_absent(student)
    return if student_absent?(student)

    Absence.create student: student, lesson: self
  end

  def mark_student_as_present(student)
    return unless student_absent? student

    absence = absences.detect { |a| a.student_id == student.id }
    absence.destroy
  end

  def student_absent?(student)
    absences.any? { |absence| absence.student_id == student.id }
  end
end

app/controllers/api/lessons_controller.rb
# frozen_string_literal: true

module Api
  class LessonsController < ApiController
    has_scope :after_timestamp
    has_scope :by_group, as: :group_id
    has_scope :by_subject, as: :subject_id

    def index
      @lessons = apply_scopes(Lesson).all
      respond_with @lessons, include: included_params, meta: { timestamp: Time.zone.now }
    end

    def show
      @lesson = Lesson.find params.require :id
      respond_with @lesson, include: included_params, meta: { timestamp: Time.zone.now }
    end

    def create
      lesson = Lesson.new lesson_params

      save_lesson lesson

      respond_with lesson, meta: { timestamp: Time.zone.now } unless performed?
    end

    private

    def lesson_params
      params.permit :group_id, :date, :subject_id
    end

    def save_lesson(lesson)
      respond_with_existing_lesson unless lesson.save
    rescue ActiveRecord::RecordNotUnique
      respond_with_existing_lesson
    end

    def respond_with_existing_lesson
      lesson = Lesson.find_by lesson_params
      respond_with(lesson, status: :ok, meta: { timestamp: Time.zone.now }) if lesson
    end
  end
end

app/controllers/lessons_controller.rb
# frozen_string_literal: true

class LessonsController < ApplicationController
  before_action do
    @lessons = policy_scope Lesson.includes(:subject, :group).all
  end

  def index
    authorize Lesson
    @lesson = Lesson.new
  end

  def show
    @lesson = Lesson.includes(:absences, :group, :subject).find(params[:id])
    authorize @lesson
    @students = @lesson.group.students.exclude_deleted
  end

  def new
    authorize Lesson
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new params.require(:lesson).permit :group_id, :date, :subject_id
    authorize @lesson
    return notice_and_redirect(t(:lesson_created), lessons_url) if @lesson.save
    render :index
  end
end

app/views/lessons/index.slim
= content_for :header_content do
  = render layout: '/shared/header_content', locals: {title: 'Lessons'} do
    = render partial: '/shared/main_header_button', locals: {href: new_lesson_path, title: 'Add Lesson'}

.single-content-card
  = render partial: 'shared/lessons_table', locals: {lessons: @lessons}

app/views/lessons/new.slim
- content_for :header_content do
  = render partial: '/shared/header_content', locals: {back_button_url: lessons_path, back_tooltip: 'Back to Lessons', title: 'New Lesson'}

.content-card--most.center
  = simple_form_for @lesson, url: {action: 'create'} do |f|
    = render partial: 'shared/errors', locals: {subject: @lesson}
    = f.association :group, label_method: :group_name, include_blank: false
    = f.association :subject, label_method: :subject_name, include_blank: false
    = f.input :date
    = f.button :submit, class: 'mdl-button--raised mdl-button--accent mdl-js-ripple-effect'

app/views/lessons/show.slim
- content_for :header_content do
  = render layout: '/shared/header_content', locals: { back_button_url: lessons_path, back_tooltip: 'Back to Lessons', title: "#{ @lesson.group.group_chapter_name } - #{ @lesson.subject.subject_name } on #{ @lesson.date }" } do


.single-content-card
  table class='mdl-data-table mdl-js-data-table resource-table'
    thead
      tr
        th class='mdl-data-table__cell--non-numeric' Last Name
        th class='mdl-data-table__cell--non-numeric' First Name
        th Average Grade

    - @students.each do |student|
      tr class='resource-row'
        td class='mdl-data-table__cell--non-numeric'
          = link_to student.last_name, lesson_student_path(@lesson.id, student.id)
        td class='mdl-data-table__cell--non-numeric'
          = link_to student.first_name, lesson_student_path(@lesson.id, student.id)
        td
          = link_to lesson_student_average_grade(@lesson, student), lesson_student_path(@lesson.id, student.id)